export const PLAYBACK_STATUS_CHANGED = 'PLAYBACK_STATUS_CHANGED';
export const MUTE_STATUS_CHANGED = 'MUTE_STATUS_CHANGED';
export const FULLSCREEN_CHANGED = 'FULLSCREEN_CHANGED';
export const CURRENT_TIME_CHANGED = 'CURRENT_TIME_CHANGED';
export const VOLUME_CHANGED = 'VOLUME_CHANGED';
export const DISABLE_CONTROLS_CHANGED = 'DISABLE_CONTROLS_CHANGED';
export const START_BUFFERING = 'START_BUFFERING';