export const CHANGE_PLAYBACK_STATUS = 'CHANGE_PLAYBACK_STATUS';
export const CHANGE_MUTE_STATUS = 'CHANGE_MUTE_STATUS';
export const CHANGE_FULLSCREEN_STATUS = 'CHANGE_FULLSCREEN_STATUS';
export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const CAN_PLAY = 'CAN_PLAY';
